name: CCTV Auto Update

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Run Python
        run: python update_cctv.py

      - name: Push GeoJSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto update CCTV" || echo "No changes"
          git push
